steps:

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args:
      - version
    env:
      - GOPATH=.

  - id: docker build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag=gcr.io/${PROJECT_ID}/${IMAGE_NAME}
      - .
# substitutions:
#   _

- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -c
  - |
    echo "This step only pushes an image to gcr.io/${PROJECT_ID}/${IMAGE_NAME} if this build was triggered on the master branch."
    [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/${PROJECT_ID}/${IMAGE_NAME}
