# These are the variables that allow us to parametrise a cloudbuild pipeline
substitutions:
  _IMAGE_NAME:

options:
  # environment variables made available to all steps
  env:
    _GOPATH=.

tags:
  - app

steps:
  - id: go version
    name: gcr.io/cloud-builders/go
    entrypoint: bash
    args:
      - -c
      - |
        go version

  - id: run unit tests
    name: gcr.io/cloud-builders/go
    entrypoint: bash
    args:
      - -c
      - |
        go test

  - id: build docker image
    waitFor: run unit tests
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --tag=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${COMMIT_SHA} \
          --tag=${COMMIT_SHA} \
          .

  # push container to GCR only if this pipeline was triggered from the master branch
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
    - -c
    - |
      if [[ "$BRANCH_NAME" == "master" ]]; then
        echo "pushing image to gcr.io/${PROJECT_ID}/${_IMAGE_NAME} as this build was triggered from the master branch"
        docker push gcr.io/${PROJECT_ID}/${_IMAGE_NAME}
      fi
